version: "3.9"

services:
  traefik:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "8081:80"  
      - "8080:8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  prensa:  
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html:ro
    labels:
      - "traefik.http.routers.prensa.rule=Host(prensa.localhost)"
      - "traefik.http.services.prensa.loadbalancer.server.port=80"

  db:  
    image: neo4j:5
    environment:
      - NEO4J_AUTH=neo4j/test123
    networks:
      - internal  

networks:
  internal:
    driver: bridge
